spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:spring_guides_batch'
    username: swszz
    password: swszz
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
  batch:
    jdbc:
      initialize-schema: "always"